<?xml version="1.0"?>
<robot xmlns:xacro="https://www.ros.org/wiki/xacro" 
	xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"	
	name="dnm">
	
  <xacro:include filename="$(find tika_ws)/xacro/wheel.xacro" />

  
  
  <!-- COLOR -->
  <material name="Black">
  	<color rgba="0 0 0 1" />
  </material>
  <material name="White">
  	<color rgba="1 1 1 1" />
  </material>
  <material name="Blue">
  	<color rgba="0 0 1 1" />
  </material>
  <material name="Red">
  	<color rgba="1 0 0 1" />
  </material>
  <material name="Steel">
  	<color rgba="0.5 0.5 0.5 1" />
  </material>
  
  <!-- All units in m-kg-s-radians unit -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="M_PI_4" value="0.785398163397448" />
  <xacro:property name="DEG_TO_RAD" value="0.017453292519943" />
  
  
  
  
  
  
  
  <xacro:property name="base_link_width" value="0.70" />
  <xacro:property name="base_link_length" value="0.70" />
  <xacro:property name="base_link_height" value="0.10" />
  
  <xacro:property name="main_arm_link_width" value="0.05" /> 
  <xacro:property name="main_arm_link_length" value="0.1" />
  <xacro:property name="main_arm_link_height" value="0.6" />
  
  <xacro:property name="sub_arm_link_width" value="0.05" />
  <xacro:property name="sub_arm_link_length" value="0.1" />
  <xacro:property name="sub_arm_link_height" value="0.3" />
  
  
  <xacro:property name="base_x_origin_to_front" value="0.35" />
  <xacro:property name="base_x_origin_to_back" value="-0.35" />
  <xacro:property name="base_y_origin_to_left" value="0.35" />
  <xacro:property name="base_y_origin_to_right" value="-0.35" />
  <xacro:property name="base_z_origin_to_base_link" value="0.6" />


  
  
  
  
  
  
  <xacro:macro name="box_inertia1" params="mass1" >
  	<inertial>
	      <mass value="${mass1}"/>
	      <inertia ixx="0.08333333333333331" iyy="0.08333333333333331" izz="0.1633333333333333"
		       ixy="0" ixz="0" iyz="0"/>
   	</inertial>
  </xacro:macro>
  <xacro:macro name="box_inertia2" params="mass2" >
  	<inertial>
	      <mass value="${mass2}"/>
	      <inertia ixx="0.015416666666666665" iyy="0.015416666666666665" izz="0.0005208333333333334"
		       ixy="0" ixz="0" iyz="0"/>
   	</inertial>
  </xacro:macro>
  <xacro:macro name="box_inertia3" params="mass3" >
  	<inertial>
	      <mass value="${mass3}"/>
	      <inertia ixx="0.015416666666666665" iyy="0.0019270833333333332" izz="0.0002604166666666667"
		       ixy="0" ixz="0" iyz="0"/>
   	</inertial>
  </xacro:macro>
  
  
  
  
  
  
  
  
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_link_width} ${base_link_length} ${base_link_height}"/>
      </geometry>
      <origin rpy="0 0 0" xyz="0 0 ${base_z_origin_to_base_link}" />
      
      <material name="Steel" />
      
    </visual>
     <collision>
   	<geometry>
   	 <box size="${base_link_width+0.1} ${base_link_length+0.1} ${base_link_height+0.1}"/>
   	</geometry>
   	<origin rpy="0 0 0" xyz="0 0 ${base_z_origin_to_base_link}" />
   
   
    </collision>
    
    <xacro:box_inertia1 mass1="2" />
    
    
  </link>
  
  
  
  <joint 
  	name="sag_arka_joint"
  	type="fixed">
  	<origin rpy="0 0 0" xyz="0 ${base_y_origin_to_right} ${base_z_origin_to_base_link}" />
  	<parent link="base_link" />
  	<child link="sag_arka_link" />
  	
  </joint>
  
  <link name="sag_arka_link">
    <visual>
      <geometry>
        <box size="${main_arm_link_width} ${main_arm_link_length} ${main_arm_link_height}"/>
      </geometry>
      <origin rpy="${-M_PI_4} 0 ${-M_PI_2}" xyz="-0.2 0 -0.20" />
      
      <material name="Steel" />
    
    </visual>
    <collision>
   	<geometry>
   	 <box size="${main_arm_link_width+0.1} ${main_arm_link_length+0.1} ${main_arm_link_height+0.1}"/>
   	</geometry>
   	<origin rpy="${-M_PI_4} 0 ${-M_PI_2}" xyz="-0.2 0 -0.20" />
    </collision>
    
    <xacro:box_inertia2 mass2="0.5" />

  </link>
  	 
   <joint 
  	name="sag_orta_joint"
  	type="fixed">
  	<origin rpy="0 0 0" xyz="-0.21 0 -0.21 " />
  	<parent link="sag_arka_link" />
  	<child link="sag_orta_link" />
  	
  </joint>
  
  <link name="sag_orta_link">
    <visual>
      <geometry>
        <box size="${sub_arm_link_width} ${sub_arm_link_length} ${sub_arm_link_height}"/>
      </geometry>
      <origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.106 0 -0.106" />
      
      <material name="Steel" />
    
    </visual>
    <collision>
   	<geometry>
   	 <box size="${sub_arm_link_width+0.1} ${sub_arm_link_length+0.1} ${sub_arm_link_height+0.1}"/>
   	</geometry>
   	<origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.106 0 -0.106" />
    </collision>
    
    <box_inertia3 mass3="0.25" />

  </link>
  
  <joint 
  	name="sag_on_joint"
  	type="fixed">
  	<origin rpy="0 0 0" xyz="0 ${base_y_origin_to_right} ${base_z_origin_to_base_link}" />
  	<parent link="base_link" />
  	<child link="sag_on_link" />
  	
  </joint>
  
  <link name="sag_on_link">
    <visual>
      <geometry>
        <box size="${main_arm_link_width} ${main_arm_link_length} ${main_arm_link_height}"/>
      </geometry>
      <origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.2 0 -0.2" />
      
      <material name="Steel" />

    </visual>
    <collision>
   	<geometry>
   	 <box size="${main_arm_link_width+0.1} ${main_arm_link_length+0.1} ${main_arm_link_height+0.1}"/>
   	</geometry>
   	<origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.2 0 -0.2" />
    </collision>
    
    <box_inertia2 mass2="0.5" />

  </link>
  
  <joint 
  	name="sol_arka_joint"
  	type="fixed">
  	<origin rpy="0 0 0" xyz="0 ${base_y_origin_to_left} ${base_z_origin_to_base_link}"/>
  	<parent link="base_link" />
  	<child link="sol_arka_link"/>
  	
  </joint>
  
  <link name="sol_arka_link">
    <visual>
      <geometry>
        <box size="${main_arm_link_width} ${main_arm_link_length} ${main_arm_link_height}"/>
      </geometry>
      <origin rpy="${-M_PI_4} 0 ${-M_PI_2}" xyz="-0.2 0 -0.20" />
      
      <material name="Steel" />

    </visual>
    <collision>
   	<geometry>
   	 <box size="${main_arm_link_width+0.1} ${main_arm_link_length+0.1} ${main_arm_link_height+0.1}"/>
   	</geometry>
   	<origin rpy="${-M_PI_4} 0 ${-M_PI_2}" xyz="-0.2 0 -0.20" />
    </collision>
    
    <box_inertia2 mass2="0.5" />

  </link>
  	 
   <joint 
  	name="sol_orta_joint"
  	type="fixed">
  	<origin rpy="0 0 0" xyz="-0.21 0 -0.21 " />
  	<parent link="sol_arka_link" />
  	<child link="sol_orta_link" />
  	
  </joint>
  
  <link name="sol_orta_link">
    <visual>
      <geometry>
        <box size="${sub_arm_link_width} ${sub_arm_link_length} ${sub_arm_link_height}"/>
      </geometry>
      <origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.106 0 -0.106" />
      
      <material name="Steel" />

    </visual>
    <collision>
   	<geometry>
   	 <box size="${sub_arm_link_width+0.1} ${sub_arm_link_length+0.1} ${sub_arm_link_height+0.1}"/>
   	</geometry>
   	<origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.106 0 -0.106" />
    </collision>
    
    <box_inertia3 mass3="0.25" />

  </link>
  
  <joint 
  	name="sol_on_joint"
  	type="fixed">
  	<origin rpy="0 0 0" xyz="0 0.35 0.6" />
  	<parent link="base_link" />
  	<child link="sol_on_link" />
  	
  </joint>
  
  <link name="sol_on_link">
    <visual>
      <geometry>
        <box size="${main_arm_link_width} ${main_arm_link_length} ${main_arm_link_height}"/>
      </geometry>
      <origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.2 0 -0.2" />
      
      <material name="Steel" />

    </visual>
    <collision>
   	<geometry>
   	 <box size="${main_arm_link_width+0.1} ${main_arm_link_length+0.1} ${main_arm_link_height+0.1}"/>
   	</geometry>
   	<origin rpy="${-M_PI_4} 0 ${M_PI_2}" xyz="0.2 0 -0.2" />
    </collision>
    
    <box_inertia2 mass2="0.5" />

  </link>
  
  
  
  <xacro:motor lr="sag" fmb="arka" translateX="-2" translateY="-1" translateZ="-2" flipY="1" />
  <xacro:motor lr="sol" fmb="arka" translateX="-2" translateY="1" translateZ="-2" flipY="1" />

  
  
  

   



  
  
  
  
  <link name="realsense_link">
   <visual>
   	<origin xyz="0 0 0.05" rpy="${M_PI_2} 0 ${M_PI_2}" />
   	<geometry>
   	 <mesh filename="package://tika_ws/meshes/d455.stl" scale="0.005 0.005 0.005"  />
   	</geometry>
   	
    <material name="Red" />

   </visual>
   <collision>
   	<geometry>
   	 <mesh filename="package://tika_ws/meshes/d455.stl" scale="0.005 0.005 0.005"  />
   	</geometry>
   	<origin xyz="0 0 0.05" rpy="${M_PI_2} 0 ${M_PI_2}" />
    </collision>
    <inertial>
      <mass value="0.05" />
      <origin xyz="0 0 0" />
      <inertia ixx="0.00156" iyy="0.00011999999999999999" izz="0.00156"
              ixy="0" iyz="0" ixz="0" />
      
    </inertial>
  </link>
  
  <joint name="realsense_joint" type="fixed">
   <parent link="base_link" />
   <child link="realsense_link" />
   <origin xyz="0.30 0 0.675" rpy="0 0 0" />
  </joint>
  
  
  <gazebo reference="world">
  	
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <gazebo reference="base_link">
  	
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <gazebo reference="sag_arka_link">
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <gazebo reference="sag_orta_link">
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  
  <gazebo reference="sag_on_link">
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <gazebo reference="sol_arka_link">
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <gazebo reference="sol_orta_link">
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <gazebo reference="sol_on_link">
  	<turnGravityOff>false</turnGravityOff>
  </gazebo>
  
  <gazebo reference="realsense_link">
   
   <turnGravityOff>false</turnGravityOff>
   <sensor type="gpu_ray" name="realsense">
    <pose>0 0 0 0 0 0</pose>
    <visualize>false</visualize>
    <update_rate>40</update_rate>
    <ray>
     <scan>
      <horizontal>
       	<samples>720</samples>
       	<resolution>1</resolution>
       	<min_angle>-1.5708</min_angle>
       	<max_angle>1.5708</max_angle>
      </horizontal>
     </scan>
     <range>
      	<min>0.10</min>
      	<max>10.0</max>
      	<resolution>0.001</resolution>
     </range>
    </ray>
    <plugin name="gpu_laser" filename="libgazebo_ros_gpu_laser.so">
     <topicName>/scan</topicName>
     <frameName>realsense_link</frameName>
    </plugin>
   </sensor>
  </gazebo>
  
  

  
  
   
  
  

  
 
  
  
</robot>

