<?xml version="1.0"?>
<robot name="motor" xmlns:xacro="https://www.ros.org/wiki/xacro">
	
 
  
  <!-- All units in m-kg-s-radians unit -->
  <xacro:property name="M_PI" value="3.1415926535897931" />
  <xacro:property name="M_PI_2" value="1.570796327" />
  <xacro:property name="M_PI_4" value="0.785398163397448" />
  <xacro:property name="DEG_TO_RAD" value="0.017453292519943" />
  <xacro:property name="D_ROOT_2" value="0.7071067812" />
  
  
  
  
  
  
  
  <xacro:property name="main_arm_link_width" value="0.05" /> 
  <xacro:property name="main_arm_link_length" value="0.1" />
  <xacro:property name="main_arm_link_height" value="0.6" />
  
  <xacro:property name="sub_arm_link_width" value="0.05" />
  <xacro:property name="sub_arm_link_length" value="0.1" />
  <xacro:property name="sub_arm_link_height" value="0.3" />
  
  <xacro:property name="wheel_mass" value="0.01" />
  <xacro:property name="wheel_length" value="0.1" />
  <xacro:property name="wheel_radius" value="0.15" />
  <xacro:property name="base_x_origin_to_front" value="0.35" />
  <xacro:property name="base_x_origin_to_back" value="-0.35" />
  <xacro:property name="base_y_origin_to_left" value="0.35" />
  <xacro:property name="base_y_origin_to_right" value="-0.35" />
  <xacro:property name="base_z_origin_to_base_link" value="0.6" />


  
  
  
  <xacro:macro name="wheel_inertia" params="wheel_mass" >
  	<inertial>
	      <mass value="${wheel_mass}"/>
        <origin xyz="0 0 0" />
	      <inertia ixx="6.458333333333335e-05" iyy="6.458333333333" izz="0.0001125"
		       ixy="0" ixz="0" iyz="0"/>
   	</inertial>
  </xacro:macro>
    

  <xacro:macro name="motor" params="lr fmb translateX translateY translateZ flipY">
    <link name="${lr}_${fmb}_motor">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
        </geometry>
        <material name="Blue" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
        <cylinder length="${wheel_length}" radius="${wheel_radius}" />
        </geometry>
      </collision>

      <xacro:wheel_inertia wheel_mass="${wheel_mass}" />
    </link>

    <joint name="${lr}_${fmb}_motor_joint" type="revolute">
      <limit effort="0" velocity="50000000" lower="-70" upper="200" />
      <parent link="${lr}_${fmb}_link" />
      <child link="${lr}_${fmb}_motor" />
      <origin xyz="${translateX*sub_arm_link_height*D_ROOT_2} ${translateY*(wheel_length/2+main_arm_link_width/2)} ${translateZ*sub_arm_link_height*D_ROOT_2}" rpy="${flipY*M_PI_2} 0 0" />
      <axis xyz="0 0 1" rpy="0 1 0" />
    </joint>

    
    
    
    <gazebo reference="${lr}_${fmb}_motor" >
      <mu1 value="0.1" />
      <mu2 value="0.1" />
      <kp value="10000.0" />
      <kd value="100.0" />
    </gazebo>


  </xacro:macro>

  <xacro:macro name="differential_motor" params="lj rj fmb_diff">
    <gazebo>
      <plugin name="differential_drive_controller"
              filename="libgazebo_ros_diff_drive.so">
        <leftJoint>${lj}_${fmb_diff}_motor_joint</leftJoint>
        <rightJoint>${rj}_${fmb_diff}_motor_joint</rightJoint>
        <robotBaseFrame>base_link</robotBaseFrame>
        <wheelSeparation>0.85</wheelSeparation>
        <wheelDiameter>0.30</wheelDiameter>
        <publishWheelJointState>true</publishWheelJointState>
        <commandTopic>cmd_vel</commandTopic>
        <odometryFrame>odom</odometryFrame>
        <odometryTopic>odom</odometryTopic>
      </plugin>
    </gazebo>
  </xacro:macro>
  

  <!--teker motorlarının urdf yedegi

  
  <link name="sag_arka_motor">
   <visual>
   	<origin xyz="0 0 0" rpy="0 0 0" />
   	<geometry>
   	 <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
   	</geometry>
   	
    <material name="Blue" />

   </visual>
   
   <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
     <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </geometry>
   </collision>
   
   <wheel_inertia wheel_mass="0.01" />

  </link>
  
  <joint name="sag_arka_motor_joint" type="continuous">
   <parent link="sag_arka_link" />
   <child link="sag_arka_motor" />
   <origin xyz="-0.42 -${wheel_length/2+main_arm_link_width/2} -0.42" rpy="${M_PI_2} 0 0" /> 
   <axis xyz="0 0 1" />
  </joint>
  
  
  
  <link name="sag_orta_motor">
   <visual>
   	<origin xyz="0 0 0" rpy="0 0 0" />
   	<geometry>
   	 <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
   	</geometry>
   	
    <material name="Blue" />

   </visual>
   
   <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
     <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </geometry>
   </collision>
   
   <wheel_inertia wheel_mass="0.01" />

  </link>
  
  <joint name="sag_orta_motor_joint" type="continuous">
   <parent link="sag_orta_link" />
   <child link="sag_orta_motor" />
   <origin xyz="0.21 -${wheel_length/2+main_arm_link_width/2} -0.21" rpy="${M_PI_2} 0 0" />
   <axis xyz="0 0 1" />
  </joint>
  
  
  <link name="sag_on_motor">
   <visual>
   	<origin xyz="0 0 0" rpy="0 0 0" />
   	<geometry>
   	 <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
   	</geometry>
   	
    <material name="Blue" />
   
   </visual>
   
   <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
     <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </geometry>
   </collision>
   
   <wheel_inertia wheel_mass="0.01" />

  </link>
  
  <joint name="sag_on_motor_joint" type="continuous">
   <parent link="sag_on_link" />
   <child link="sag_on_motor" />
   <origin xyz="0.42 -${wheel_length/2+main_arm_link_width/2} -0.42" rpy="${M_PI_2} 0 0" /> 
   <axis xyz="0 0 1" />
  </joint>
  
  
  <link name="sol_arka_motor">
   <visual>
   	<origin xyz="0 0 0" rpy="0 0 0" />
   	<geometry>
   	 <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
   	</geometry>
   	
    <material name="Blue" />

   </visual>
   
   <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
     <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </geometry>
   </collision>
   
   <wheel_inertia wheel_mass="0.01" />

  </link>
  
  <joint name="sol_arka_motor_joint" type="continuous">
   <parent link="sol_arka_link" />
   <child link="sol_arka_motor" />
   <origin xyz="-0.42 ${main_arm_link_width/2+wheel_length/2} -0.42" rpy="${M_PI_2} 0 0" />
   <axis xyz="0 0 1" />
  </joint>
  
  <link name="sol_orta_motor">
   <visual>
   	<origin xyz="0 0 0" rpy="0 0 0" />
   	<geometry>
   	 <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
   	</geometry>
   	
    <material name="Blue" />

   </visual>
   
   <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
     <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </geometry>
   </collision>
   
   <wheel_inertia wheel_mass="0.01" />

  </link>
  
  <joint name="sol_orta_motor_joint" type="continuous">
   <parent link="sol_orta_link" />
   <child link="sol_orta_motor" />
   <origin xyz="0.21 ${main_arm_link_width/2+wheel_length/2} -0.21" rpy="${M_PI_2} 0 0" />
   <axis xyz="0 0 1" />
  </joint>


  <link name="sol_on_motor">
   <visual>
   	<origin xyz="0 0 0" rpy="0 0 0" />
   	<geometry>
   	 <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
   	</geometry>
   	
    <material name="Blue" />

   </visual>
   
   <collision>
    <origin xyz="0 0 0" rpy="0 0 0" />
    <geometry>
     <cylinder length="${wheel_length}" radius="${wheel_radius}"/>
    </geometry>
   </collision>
   
   <wheel_inertia wheel_mass="0.01" />
   
  </link>
  
  <joint name="sol_on_motor_joint" type="continuous">
   <parent link="sol_on_link" />
   <child link="sol_on_motor" />
   <origin xyz="0.42 ${main_arm_link_width/2+wheel_length/2} -0.42" rpy="${M_PI_2} 0 0" />
   <axis xyz="0 0 1" />
  </joint>
  
  
   
   <gazebo reference="sag_arka_motor">
   <mu1 value="0.1" />
   <mu2 value="0.1" />
   <kp value="10000.0" />
   <kd value="100.0" />
   
   
  </gazebo>
  
  <gazebo reference="sag_orta_motor">
   <mu1 value="0.1" />
   <mu2 value="0.1" />
   <kp value="10000.0" />
   <kd value="100.0" />
   

  </gazebo>
  
  <gazebo reference="sag_on_motor">
   <mu1 value="0.1" />
   <mu2 value="0.1" />
   <kp value="10000.0" />
   <kd value="100.0" />
   
   
  </gazebo>
  
  <gazebo reference="sol_arka_motor">
   <mu1 value="0.1" />
   <mu2 value="0.1" />
   <kp value="10000.0" />
   <kd value="100.0" />
   
   
  </gazebo>
  
  <gazebo reference="sol_orta_motor">
   <mu1 value="0.1" />
   <mu2 value="0.1" />
   <kp value="10000.0" />
   <kd value="100.0" />
   
  </gazebo>
   
   
   <gazebo reference="sol_on_motor">
   <mu1 value="0.1" />
   <mu2 value="0.1" />
   <kp value="10000.0" />
   <kd value="100.0" />
   
   
  </gazebo> -->
  
</robot>



  
  













